baseURL      = "https://kone.js.cn/"
languageCode = "zh"
title        = "欢迎来到我的世界"
# title        = "Welcome to My world"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"


[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
