mainSections   = ["post"]
rssFullContent = true
favicon        = "img/favicon.jpeg"

[footer]
    since = 2026
    customText = "Designed by âœ§Kà¼ºOà¼’Nà¼»Eâœ§"

[sidebar]
    emoji    = "ðŸš€"
    subtitle = "æ¸´æœ›è‡ªå·±å†³å®šï¼Œæ¸´æœ›é¼“èˆžä»–äºº"
    avatar   = "img/avatar.jpg"

[article]
    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "waline"

    # Waline client configuration see: https://waline.js.org/en/reference/component.html
    [comments.waline]
        serverURL = "https://waline.kone.js.cn/"
        lang = "zh-CN"
        pageview = true
        emoji = [
            "https://unpkg.com/@waline/emojis@1.0.1/weibo"
        ]
        requiredMeta = [
            "nick"
        ]
